name: Continues Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SINGLE_FILE: "true"

jobs:
  continues_integration:
    name: Run continues integration for ${{ github.event_name }} event
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./cli

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet nuget add source --username martijnvanschie --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/martijnvanschie/index.json"
        dotnet restore
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd Azure.Purview.Cli
        dotnet publish -p:PublishSingleFile=$SINGLE_FILE --runtime win-x64 --configuration Release --no-self-contained --output ../../publish/
    - name: Upload a Build Artifact
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/upload-artifact@v3.0.0
      with:
        name: cli
        path: publish/